export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HEAD_SUPERVISOR: 'HEAD_SUPERVISOR',
  SITE_SUPERVISOR: 'SITE_SUPERVISOR',
  AUDITOR: 'AUDITOR',
  OPERATOR: 'OPERATOR',
} as const

export type Role = (typeof Role)[keyof typeof Role]

export const ROLE_LEVELS: Record<Role, number> = {
  SUPER_ADMIN: 5,
  HEAD_SUPERVISOR: 4,
  SITE_SUPERVISOR: 3,
  AUDITOR: 2,
  OPERATOR: 1,
}

export const ROLE_LABELS: Record<Role, string> = {
  SUPER_ADMIN: 'Super Admin',
  HEAD_SUPERVISOR: 'Chef Superviseur',
  SITE_SUPERVISOR: 'Superviseur',
  AUDITOR: 'Auditeur',
  OPERATOR: 'Opérateur',
}

export const Permission = {
  VIEW_ALL_USERS: 'VIEW_ALL_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  CHANGE_USER_ROLE: 'CHANGE_USER_ROLE',
  ASSIGN_SITES: 'ASSIGN_SITES',
  ASSIGN_ZONES: 'ASSIGN_ZONES',

  VIEW_ALL_SITES: 'VIEW_ALL_SITES',
  VIEW_OWN_SITES: 'VIEW_OWN_SITES',
  CREATE_SITE: 'CREATE_SITE',
  UPDATE_SITE: 'UPDATE_SITE',
  DELETE_SITE: 'DELETE_SITE',
  ASSIGN_SUPERVISOR: 'ASSIGN_SUPERVISOR',

  VIEW_ALL_ZONES: 'VIEW_ALL_ZONES',
  VIEW_OWN_ZONES: 'VIEW_OWN_ZONES',
  CREATE_ZONE: 'CREATE_ZONE',
  UPDATE_ZONE: 'UPDATE_ZONE',
  DELETE_ZONE: 'DELETE_ZONE',
  ASSIGN_OPERATOR: 'ASSIGN_OPERATOR',

  VIEW_CONFIG: 'VIEW_CONFIG',
  UPDATE_AIRFLOW: 'UPDATE_AIRFLOW',
  UPDATE_WEIGHTS: 'UPDATE_WEIGHTS',
  UPDATE_TARGETS: 'UPDATE_TARGETS',

  VIEW_THRESHOLDS: 'VIEW_THRESHOLDS',
  UPDATE_THRESHOLDS: 'UPDATE_THRESHOLDS',

  VIEW_ALERTS: 'VIEW_ALERTS',
  ACKNOWLEDGE_ALERT: 'ACKNOWLEDGE_ALERT',
  ESCALATE_ALERT: 'ESCALATE_ALERT',
  RESOLVE_ALERT: 'RESOLVE_ALERT',

  VIEW_KPI: 'VIEW_KPI',
  GENERATE_REPORT: 'GENERATE_REPORT',
  SUBMIT_ANPE: 'SUBMIT_ANPE',

  VIEW_AI: 'VIEW_AI',
  RETRAIN_MODEL: 'RETRAIN_MODEL',
} as const

export type Permission = (typeof Permission)[keyof typeof Permission]

const allPermissions = Object.values(Permission) as Permission[]

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: allPermissions,

  HEAD_SUPERVISOR: [
    'VIEW_ALL_USERS',
    'VIEW_ALL_SITES',
    'VIEW_ALL_ZONES',
    'CREATE_SITE',
    'UPDATE_SITE',
    'CREATE_ZONE',
    'UPDATE_ZONE',
    'ASSIGN_SUPERVISOR',
    'ASSIGN_OPERATOR',
    'VIEW_CONFIG',
    'VIEW_THRESHOLDS',
    'VIEW_ALERTS',
    'ACKNOWLEDGE_ALERT',
    'ESCALATE_ALERT',
    'RESOLVE_ALERT',
    'VIEW_KPI',
    'GENERATE_REPORT',
    'VIEW_AI',
    'RETRAIN_MODEL',
  ],

  SITE_SUPERVISOR: [
    'VIEW_OWN_SITES',
    'VIEW_OWN_ZONES',
    'UPDATE_SITE',
    'CREATE_ZONE',
    'UPDATE_ZONE',
    'ASSIGN_OPERATOR',
    'VIEW_CONFIG',
    'VIEW_THRESHOLDS',
    'VIEW_ALERTS',
    'ACKNOWLEDGE_ALERT',
    'ESCALATE_ALERT',
    'VIEW_KPI',
    'GENERATE_REPORT',
    'VIEW_AI',
  ],

  AUDITOR: [
    'VIEW_ALL_USERS',
    'VIEW_ALL_SITES',
    'VIEW_ALL_ZONES',
    'VIEW_CONFIG',
    'VIEW_THRESHOLDS',
    'VIEW_ALERTS',
    'VIEW_KPI',
    'VIEW_AI',
    'GENERATE_REPORT',
  ],

  OPERATOR: [
    'VIEW_OWN_ZONES',
    'VIEW_ALERTS',
    'ACKNOWLEDGE_ALERT',
    'VIEW_KPI',
  ],
}
